services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=tds_wrhs
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - tds-network

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=tds_wrhs
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - tds-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - tds-network

volumes:
  postgres_data:
  redis_data:

networks:
  tds-network:
    driver: bridge
