services:
  api:
    image: ghcr.io/les-holikov/knossos-api:${IMAGE_TAG:-latest}
    container_name: api
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - tds_network
 
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    networks:
      - tds_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  redis_data:

networks:
  tds_network:
    name: tds_network
    driver: bridge
